### ISSUE TITLE
Go get command not working. 

### ISSUE THREAD

**Issue by ankitsnlq** [goraft/raftd#20]
Hi, 

I have done setting GOPATH and installed git also. But after giving command 
```go get github.com/goraft/raftd```

It gives Error and installtion fails. Here is error.

```package code.google.com/p/gogoprotobuf/proto: unable to detect version control system for code.google.com/ path
package code.google.com/p/goprotobuf/proto: unable to detect version control system for code.google.com/ path```

**Comment by philips** [comment]
raftd and go-raft are unmaintained: https://github.com/goraft/raft#project-status

I would suggest looking at this: https://github.com/coreos/etcd/tree/master/contrib/raftexample
